name: reddit_tutorial
description: "Clone of Reddit by Rivaan"
publish_to: "none" 
version: 1.0.1+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.17.0
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.10.1
  firebase_storage: ^11.4.1

  any_link_preview: ^3.0.1
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  file_picker: ^6.1.1
  flutter_riverpod: ^2.4.3
  fpdart: ^1.1.0
  google_sign_in: ^6.1.5
  routemaster: ^1.0.1
  shared_preferences: ^2.0.15
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google.png
    - assets/images/loginEmote.png
    - assets/images/logo.png
    - assets/images/awards/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
