// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgZQ3i9fbnqUuvAvj5vdGYY_RJIlb55xA',
    appId: '1:946451723517:web:f3ddf26078a4dbe26efa94',
    messagingSenderId: '946451723517',
    projectId: 'adapt-or-die',
    authDomain: 'adapt-or-die.firebaseapp.com',
    storageBucket: 'adapt-or-die.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfb-VSCwXV1k_mCITA3aMehdZ0nYkViio',
    appId: '1:946451723517:android:3cdd53b76b048da56efa94',
    messagingSenderId: '946451723517',
    projectId: 'adapt-or-die',
    storageBucket: 'adapt-or-die.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkLjsVaNebqfiajDXY9eK56AfD2iRvf0Q',
    appId: '1:946451723517:ios:3c98d9630da957c86efa94',
    messagingSenderId: '946451723517',
    projectId: 'adapt-or-die',
    storageBucket: 'adapt-or-die.appspot.com',
    iosBundleId: 'com.example.flutterRedditClone',
  );
}
